### ISSUE TITLE
el-select multiple mode doesn't work with initial values

### ISSUE THREAD

**Issue by yinjs** [ElemeFE/element-angular#79]
Issue Type:
- [x] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  
0.7.2

Description:
el-select multiple mode doesn't work with initial values.

[https://stackblitz.com/edit/angular-8rupqm](https://stackblitz.com/edit/angular-8rupqm)

**Comment by WittBulter** [comment]
fixed. 
upgrade version plz.

**Comment by yinjs** [comment]
@WittBulter 
Still not work in formGroup. Please check the example

[https://stackblitz.com/edit/angular-8rupqm](https://stackblitz.com/edit/angular-8rupqm)
